# Generated by Django 3.0.4 on 2020-03-22 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutme',
            name='profile_picture',
        ),
    ]
