# Generated by Django 3.0.4 on 2020-03-22 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0002_remove_aboutme_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='profile_img',
            field=models.ImageField(default='null', upload_to='images/'),
            preserve_default=False,
        ),
    ]
