# Generated by Django 3.0.4 on 2020-03-26 07:02

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0003_aboutme_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutme',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
