# Generated by Django 3.0.4 on 2020-03-26 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0005_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='iconClass',
            field=models.CharField(default='fa fa-search', max_length=50),
        ),
    ]
