# Generated by Django 3.0.4 on 2020-03-26 07:33

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0006_services_iconclass'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(max_length=200)),
                ('section_description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('user_message', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('user_name', models.CharField(max_length=200)),
                ('user_position', models.CharField(max_length=200)),
                ('user_image', models.ImageField(upload_to='')),
            ],
        ),
    ]
