# Generated by Django 3.0.4 on 2020-03-26 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0007_testimonial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='section_description',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='section_title',
        ),
    ]
