# Generated by Django 3.0.4 on 2020-03-26 08:30

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0008_auto_20200326_0740'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=200)),
                ('project_short_desc', models.TextField()),
                ('project_full_desc', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('project_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='display.Category')),
            ],
        ),
    ]
