# Generated by Django 3.0.4 on 2020-03-26 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0009_category_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_profile_image',
            field=models.ImageField(default='null', upload_to=''),
            preserve_default=False,
        ),
    ]
