# Generated by Django 3.0.4 on 2020-03-26 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0011_projectimages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectimages',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='Project_images',
            field=models.ManyToManyField(to='display.ProjectImages'),
        ),
    ]
