# Generated by Django 3.0.4 on 2020-03-26 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0012_auto_20200326_0937'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectimages',
            old_name='image_title',
            new_name='image_alternative',
        ),
    ]
